services:
  - type: web
    name: batchgrad-api
    env: node
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/puppeteer
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
